### ISSUE TITLE
Intrinsic Parameters Missing?

### ISSUE THREAD

**Issue by jingyushi** [LeylaKhaleghi/MuViHand#1]
It seems that you are not providing the intrinsic parameters of the cameras. I only saw the extrinsic matrices in each folder.

**Comment by LeylaKhaleghi** [comment]
Thank you for mentioning that. It was a typo error in the dataset description that was found last week. It will be corrected shortly. The extrinsic matrix has just been provided. 2D pixel values are already calculated and have been provided. I wish that would help. 

Best, 
Leyla
