### ISSUE TITLE
How to Get Locations of the Hand Joints?

### ISSUE THREAD

**Issue by sysu19351017** [LeylaKhaleghi/MuViHand#3]
It‘s quite cool to build a dataset in this way! I’m very interested in your work. 

Now I’m trying to build a dataset according to the way mentioned in your paper “Multi-View Video-Based 3D Hand Pose Estimation”, but I’ve encountered the following problems. I hope I can get your help. 
I can’t get the 2D & 3D locations of the hand joints in Blender. I wonder how you achieved this in your research, which is not described in detail in the paper. Did you use a script from Blender or something else? 

Thanks in advanced!

**Comment by LeylaKhaleghi** [comment]
yes,  you can access the bone position in a blender (3D word coordinate), and if you have the camera matrix, you can have the 3D camera coordinate and 2D location. I barely remember how I coded two years ago, but maybe using the link here, you can get an idea of how I coded then. This forum has all the hints I remember finding.

https://blender.stackexchange.com/questions/15353/get-the-location-in-world-coordinates-of-a-bones-head-and-tail-while-in-pose-mo

**Comment by sysu19351017** [comment]
Thanks so much! I'll check the forum and have a try.
